name: Test
on: push


concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        version:
          - "redis:latest"
          - "redis:7"

    runs-on: ubuntu-latest
    container:
      image: clojure:openjdk-11-lein-2.9.6
    services:
      redis:
        image: ${{ matrix.version }}
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4.2.2

    - name: Cache deps
      uses: actions/cache@v4.2.2
      with:
        path: /home/runner/.m2
        key: v1-deps-${{ hashFiles('project.clj') }}
        restore-keys: |
          v1-deps-${{ hashFiles('project.clj') }}
          v1-deps-

    - name: Install dependencies
      run: lein deps

    - name: Run omega-red tests for ${{ matrix.version }}
      id: tests
      run: lein test 2>&1
      env:
        REDIS_HOST: redis
        REDIS_PORT: 6379
